# script to restart pesky SmartNAV with powershell, and sometimes stupid policy prevents the other version from running as admin
# this one should not require admin rights
# I find that smartnav is always dying on me in windows 10, so I'm constantly restarting it, usually
# after machine sleeps
# create a shortcut to this, like C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command "C:\foo\bar\thisfile.ps1"
wmic process where "name='SmartNAV.exe'" delete
Start-Process "C:\Program Files (x86)\NaturalPoint\SmartNav\SmartNAV.exe"
# SIG # Begin signature block
# MIIFjgYJKoZIhvcNAQcCoIIFfzCCBXsCAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUUtCrtprwHdeTirEbJJDIYFHI
# /bqgggMeMIIDGjCCAgKgAwIBAgIQXGoxlt1ok7FP9R6mcjA1MzANBgkqhkiG9w0B
# AQUFADAlMSMwIQYDVQQDDBpMVyBQb3dlcnNoZWxsIENvZGUgU2lnbmluZzAeFw0y
# NDA2MTkxMzM2NDFaFw0yNTA2MTkxMzU2NDFaMCUxIzAhBgNVBAMMGkxXIFBvd2Vy
# c2hlbGwgQ29kZSBTaWduaW5nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
# AQEAzkXOGgF7IbhOOXG7VsWOrAyX8DwJFye71Jf6GdWNd0Do0l1eyym2EArC886S
# XMm7wQFwDRFTW2Ctan/K4cF18Ew6Cz3ruJd3xltx/hsa9TexKFEoSTzUeWL3ej+n
# bYyKrrBQlT/k0kAkJt+3mk6Iqhd3NDzA/XwLElXq8FpzdYQZZjdiSapMcez3lKdt
# 8beI1YQSqob1UwHX5pEdHyrQkQbmhzcRmORtU+cDB10WW/bgB2J5oy8JcxALW2SJ
# XU0R/Kvpb/i+KFxe9b9b32N92lJkRH8mnDe6xBLgsNlAufOdQ2oYbhcAQWAneeL+
# qg7P3HieeVKAMap+8BHFJwIJRQIDAQABo0YwRDAOBgNVHQ8BAf8EBAMCB4AwEwYD
# VR0lBAwwCgYIKwYBBQUHAwMwHQYDVR0OBBYEFPAGoM68OBIdX9k9dPxOG21TPOPT
# MA0GCSqGSIb3DQEBBQUAA4IBAQA8ipeaRA9tqqWEpr+gLPVk/EtmqCCoZLqvVK8h
# 2kCLRMnJGEODm1Hv9UGJSucH9CN89OqviPzj7BSMzZpx7oaKFDkEWWspFM4v1YEO
# /5d20BHjYejO08RzblJ9VN4zi+eJ5fGLj5gnpEqxM5Gid34HJb/jMbRhQl9xJZB0
# Z0Q3a9e0OKQqryezE0vmFEzNKuFHzpdFhuGpH0AmutVazaf4scenpLaPHkFsTc2c
# 1z78GJaQEs3YjSWKK20U1aI5cXgXtkhNSzL+D6LYzZyrFwTokklawyrhctl2jQAt
# N1OVNSCll2VDOFAdLevVaKcvOB2CnZXaej566woQPngZtIf5MYIB2jCCAdYCAQEw
# OTAlMSMwIQYDVQQDDBpMVyBQb3dlcnNoZWxsIENvZGUgU2lnbmluZwIQXGoxlt1o
# k7FP9R6mcjA1MzAJBgUrDgMCGgUAoHgwGAYKKwYBBAGCNwIBDDEKMAigAoAAoQKA
# ADAZBgkqhkiG9w0BCQMxDAYKKwYBBAGCNwIBBDAcBgorBgEEAYI3AgELMQ4wDAYK
# KwYBBAGCNwIBFTAjBgkqhkiG9w0BCQQxFgQUeGLrjFzIlmS6WOKHGkgSm1kTWJYw
# DQYJKoZIhvcNAQEBBQAEggEAcvol9klFe0TgLgUk1tkSg8BhwUy9FwTrK5m6MTqV
# fq+cCy4ZJQtAs3XpPHPuxKdH42ZwfgEErUTwzN7Nsp2bElE7tBGok8XCOcDtwNMM
# BXvB8Vgd8wgpWHHD2bKiyE3N4uhEoTYZYPekl5j+p3JLllP7+kA+ofCraBbDYj0e
# 9XPxThThGCC7paJjXkZ9SzYQSO2O4XenUOGUvGpm8M8Pp5cUQvKc7yUWuo6DGNQv
# aCu64N1c5R08+cpLbYhvxS8rXJXGPlCNVp0sxs1jxdpGrbBsb1V7+rnb0T8H+j4d
# rHvA7Bu5x/ckOy+yUEHqOp2Bs9xe9GiYNtkrB+FudbX+Yg==
# SIG # End signature block
